version: '3.9'

services:

  db:
    image: postgres:15.3-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: collaberr
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: collaberr
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      CORE_SETTING_DATABASES: '{"default":{"HOST":"db"}}'

volumes:
  postgresql-data:
    driver: local
