name: Docker Image CI

on:
  pull_request:
    branches: [ "staging" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Docker Hub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build Docker image
      run: |
        docker compose build
    - name: Tag Docker images
      run: | 
        docker image tag tonylee9692/collaberr-backend-staging:latest tonylee9692/collaberr-backend-staging:app
    - name: Push Docker images
      run: |
        docker push tonylee9692/collaberr-backend-staging:app
